# yazi.toml
[mgr]
show_hidden = true

[opener]
md-preview = [
        { run = 'mo-opener "$@"', orphan = true, desc = "Preview Markdown in browser" }
]

[open]
prepend_rules = [
        { url = "*.md", use = [ "md-preview", "edit" ] }
]
